[build]
  # Perintah yang dijalankan Netlify untuk mempersiapkan situs
  # Ini akan menginstal library Python
  command = "pip install -r requirements.txt"

  # Direktori yang berisi file statis yang akan disajikan langsung oleh Netlify
  # Pastikan semua aset statis (termasuk CSS, JS, Gambar, robots.txt, sitemap.xml) ada di sini
  publish = "static"

# Konfigurasi untuk Netlify Functions
[functions]
  # Direktori tempat fungsi serverless Anda berada
  # Anda perlu menempatkan kode fungsi Python Anda di sini
  directory = "netlify/functions"
  # Runtime yang digunakan (opsional, Netlify biasanya mendeteksi)
  # runtime = "python"

# Redirects untuk mengarahkan permintaan ke fungsi Flask Anda
# Ini diperlukan karena halaman utama dan rute non-statis akan ditangani oleh Flask
[[redirects]]
  from = "/"
  to = "/.netlify/functions/app" # Ganti dengan nama file fungsi Anda (tanpa .py)
  status = 200

[[redirects]]
  from = "/*" # Mengarahkan semua permintaan lain (non-statis)
  to = "/.netlify/functions/app"
  status = 200
  force = true # Penting untuk memastikan redirect ini dijalankan bahkan jika ada file statis lain yang cocok